### ISSUE TITLE
GCB site down

### ISSUE THREAD

**Issue by Athandreyal** [gcblue/gcblue#36]
@dewitt1 trying this to hedge my bet and try to ensure you're notified of this

The only contact I have for you is GCBlue.com, which, as you know, is well, going to be offline soon, if not already by the time you see this.

We need to talk about its future some more, I have plans to take over the account, but can not register the same domain until the current expired, and do not know enough to take over the current, especially since I do not want an empty forum, but if possible, to resume the old forum as it was at the time it went down.

I'm hoping that either you used a different email than the GCBlue email for this account, or that you do still have access to that email address, because otherwise, I have now lost contact and that is that.

**Comment by dewitt1** [comment]
If you create a site that can host phpbb3, i can set it up for you. I have a recent backup of the forum I can use. You can reach me at dewitt@programmer.net

**Comment by Athandreyal** [comment]
I suppose this is overdue, but I should close this now that its been resolved.

Site has been rehosted at forum.gcblue2.com

**Comment by fernandosteven95** [comment]
El sitio ya está clausurado, si alguien conoce como activar el multijugador, o un juego similiar que simule operaciones navales, le agradecería mucho que me escribiera.
fernandosteven95@gmail.com
